#ifndef AopaImTypes_h
#define AopaImTypes_h

// 枚举定义
typedef NS_ENUM(NSInteger, IMStatus) {
    BMSG_RESULT_OK = 0
};

typedef NS_ENUM(NSInteger, ErrorCode) {
    BMSG_CODE_OK = 0,
    BMSG_ERR_CANCELLED = 1,
    BMSG_ERR_SERVER_UNKNOWN = 2,
    BMSG_ERR_INVAILD_PARAM = 3,
    BMSG_ERR_DEADLINE_EXCEEDED = 4,
    BMSG_ERR_CANNOT_FIND = 5,
    BMSG_ERR_ALREADY_EXISTS = 6,
    BMSG_ERR_PERMISSION_DENIED = 7,
    BMSG_ERR_RESOURCE_EXHAUSTED = 8,
    BMSG_FERR_AILED_PRECONDITION = 9,
    BMSG_ERR_ABORTED = 10,
    BMSG_ERR_OUT_OF_RANGE = 11,
    BMSG_ERR_UNIMPLEMENTED = 12,
    BMSG_ERR_SERVER_INTERNAL = 13,
    BMSG_ERR_UNAVAILABLE = 14,
    BMSG_ERR_DATA_LOSS = 15,
    BMSG_ERR_AUTH_FAILED = 16,
    BMSG_ERR_ALREADY_LOGINED = 17,
    
    BMSG_ERR_FILE_UPLOAD_FAILED = 100,
    BMSG_ERR_NO_FOUND_MESSAGE = 101,
    BMSG_ERR_NO_FOUND_CONVERSATION = 102,
    BMSG_ERR_DB_OPT_ERROR = 103,
    BMSG_ERR_LOGIN = 104
};

typedef NS_ENUM(NSInteger, MessageType) {
    BMSG_TYPE_UNIVERSAL = 0,
    BMSG_TYPE_TEXT = 1,
    BMSG_TYPE_IMAGE = 2,
    BMSG_TYPE_GIF = 3,
    BMSG_TYPE_VOICE = 4,
    BMSG_TYPE_VIDEO = 5,
    BMSG_TYPE_FILE = 6,
    BMSG_TYPE_LOCATION = 7,
    BMSG_TYPE_INFO = 8,
    BMSG_TYPE_CMD = 9,
    BMSG_TYPE_RECALL = 10,
    BMSG_TYPE_READRECEIPT = 11,
    BMSG_TYPE_TYPING = 12,
    BMSG_TYPE_NOTIFICATION = 14,
    BMSG_TYPE_MENTIONED = 15,
    BMSG_TYPE_DELETE = 18
};

typedef NS_ENUM(NSInteger, ConversationType) {
    BMSG_MSG_TYPE_UNIVERSAL = 0,
    BMSG_PRIVATE_CHAT = 1,
    BMSG_GROUP_CHAT = 2,
    BMSG_ROOM_CHAT = 3
};

typedef NS_ENUM(NSInteger, DirectionType) {
    BMSG_DIRECTION_SEND = 0,
    BMSG_DIRECTION_RECEIVE = 1
};

typedef NS_ENUM(NSInteger, MessageStatus) {
    BMSG_STATUS_SENDING = 0,
    BMSG_STATUS_FAILED,
    BMSG_STATUS_SENT,
    BMSG_STATUS_RECEIVED,
    BMSG_STATUS_READ,
    BMSG_STATUS_RECEIVED_READ,
    BMSG_STATUS_DELETE,
    BMSG_STATUS_DESTROYED
};

typedef NS_ENUM(NSInteger, MentionType) {
    BMSG_MENTION_TYPE_NONE = 0,
    BMSG_MENTION_TYPE_USERS = 1,
    BMSG_MENTION_TYPE_ALL = 2
};

typedef NS_ENUM(NSInteger, ConnectStatus) {
    BMSG_STATUS_DISCONNECT,
    BMSG_STATUS_CONNECTING,
    BMSG_STATUS_CONNECTED,
    BMSG_STATUS_LOGGING_IN,
    BMSG_STATUS_LOGINED,
    BMSG_STATUS_LOGOUT
};


#endif /* AopaImTypes_h */